# Green–Lagrange Strain Tensor [1]

The **Green–Lagrange strain tensor** is directly defined in terms of the right Cauchy–Green deformation tensor by:

$$
\mathbf{E} = \frac{1}{2} (\mathbf{C} - \mathbf{I})
$$

where $\mathbf{I}$ is the identity tensor, and its components are denoted $E_{ij}$ with $i, j = 1, \dots, 3$.

As with the strain tensor components, the values depend on the basis in which they are written. Some formulations use the **strain invariants** to express the constitutive law. For isotropic media, these invariants are given by:

$$
\begin{aligned}
I_1 &= \text{tr}(\mathbf{C}) \\
I_2 &= \frac{1}{2} \left[ \text{tr}(\mathbf{C})^2 - \text{tr}(\mathbf{C}^2) \right] \\
I_3 &= \det(\mathbf{C})
\end{aligned}
$$

where `tr` is the trace operator, and `det` is the determinant operator.

## Cauchy-Green Tensors [1]

The deformation of soft tissues is often described by means of the **right and left Cauchy–Green tensors**, defined as:

$$
\mathbf{C} = \mathbf{F}^\mathrm{T} \mathbf{F} \quad \text{and} \quad 
\mathbf{B} = \mathbf{F} \mathbf{F}^\mathrm{T}
$$

where $\mathbf{F}$ is the deformation gradient.  

The **principal components** of the right or left Cauchy–Green tensors are $\lambda_i^2$ with $i = 1, \dots, 3$, where $\lambda_i$ are the **principal stretches**.  

## Deformation Gradient [2]

The **deformation gradient** $\mathbf{F}$ is defined by:

$$
\mathbf{F} = \frac{\partial \mathcal{X}(\mathbf{X}, t)}{\partial \mathbf{X}}
$$

which in **index notation** can be written as:

$$
F_{ij} = \frac{\partial x_i}{\partial X_j}
$$

The deformation gradient is a very important descriptor of the applied deformation state and is extensively used in both theoretical and computational works.



---

### Reference

[1] Chagnon, G., Ohayon, J., Martiel, J.-L., & Favier, D. (2017). *Hyperelasticity modeling for incompressible passive biological tissues.* In Y. Payan & J. Ohayon (Eds.), *Translational epigenetics: Biomechanics of living organs* (Vol. 1, pp. 3–30). Academic Press. [https://doi.org/10.1016/B978-0-12-804009-6.00001-8](https://doi.org/10.1016/B978-0-12-804009-6.00001-8)

[2] Bergström, J. S. (2015). *Continuum mechanics foundations.* In *Mechanics of Solid Polymers: Theory and Computational Modeling* (pp. 131–207). William Andrew Publishing. [https://doi.org/10.1016/B978-0-323-31150-2.00004-2](https://doi.org/10.1016/B978-0-323-31150-2.00004-2)




In [1]:
path="fullSpatialJacobian.nii"

In [2]:
import numpy as np
import pyvista as pv
import SimpleITK as sitk
from pathlib import Path

# Read deformation gradient
File = Path(path)
Jacobian = sitk.ReadImage(File)
Jacobian = sitk.GetArrayFromImage(Jacobian)
Jacobian = Jacobian.transpose((2,1,0,3))

# Build deformation gradient field
F_Field = np.zeros(Jacobian.shape[:-1] + (3,3))
for i in range(3):
    for j in range(3):
        F_Field[...,i,j] = Jacobian[...,-(i*3+j)-1]

# Determinant of F
J = np.linalg.det(F_Field)

# Right Cauchy–Green tensor
C = np.einsum('...ki,...kj->...ij', F_Field, F_Field)
print(f'Tensor C and image center:\n {C[32,32,32].round(3)}')


Tensor C and image center:
 [[ 0.  0.  0.]
 [ 0.  0. -0.]
 [ 0. -0.  1.]]


In [3]:
# Green–Lagrange strain tensor
I = np.eye(3)
I3 = np.ones(C.shape)
for i in range(C.shape[0]):
    for j in range(C.shape[1]):
        for k in range(C.shape[2]):
            I3[i,j,k] = I
E = 0.5 * (C - I3)

print("E (Green–Lagrange strain) at center voxel:")
print(E[32, 32, 32].round(4))


E (Green–Lagrange strain) at center voxel:
[[-5.e-01  0.e+00  0.e+00]
 [ 0.e+00 -5.e-01 -0.e+00]
 [ 0.e+00 -0.e+00 -2.e-04]]


In [4]:
# Green–Lagrange strain tensor
I = np.eye(3)
E = 0.5 * (C - I)

print("E (Green–Lagrange strain) at center voxel:")
print(E[32, 32, 32].round(4))


E (Green–Lagrange strain) at center voxel:
[[-5.e-01  0.e+00  0.e+00]
 [ 0.e+00 -5.e-01 -0.e+00]
 [ 0.e+00 -0.e+00 -2.e-04]]
